### PR TITLE
Basic handling of implicit arguments and return value for subroutines / functions.

### PR DESCRIPTION
**Pull request by MrYann**

### CODE REVIEW

**Comment by jameskermode** [comment]
Can you have a look at the failing tests? You can run them locally from Makefile in examples directory.

**Comment by MrYann** [comment]
Hah. I was not aware that functions could have stuff before their name. I have put the "get function name" back to it's old place and everything seems to be fine.

**Comment by jameskermode** [comment]
Looks good, merging and closing pull request. Many thanks for this contribution!

**Comment by MrYann** [comment]
Nice. Thanks to you :)
Now let’s deal with the pointer arguments. Do you have any lead as to why they are not supported ? (i did no extensive testing, but f2py seems to support them)
____
Yann

**Pull request closed without merging**
