### PR TITLE
'module procedure' was parsed without ignoring the case

### PR DESCRIPTION
**Pull request by mcuntz**
The line
prototype = re.compile(r'^module procedure ([a-zA-Z0-9_,\s]*)')
in parser.py did not include re.IGNORECASE so 'module procedure' had to be written in lower case in order for interfaces to work.
For example:
INTERFACE sort
    MODULE PROCEDURE sort_sp, sort_dp
end interface sort
did not work.
INTERFACE sort
    module procedure sort_sp, sort_dp
end interface sort
worked.

There are four other lines fdoc_*, that deal with the documentation, that do also not ignore the case. I do not know if this is wanted or not. I am still using doxygen to document my Fortran code.

Kind regards
Matthias

### CODE REVIEW

**Comment by jameskermode** [comment]
Thanks for this contribution, I'll be happy to merge. Before I can do this, please remove the change to `version`, this should only be updated when making a new release.

**Comment by jameskermode** [comment]
Please also take a look at the failing test - you can run these yourself with `make test` from the `examples/` directory.

**Comment by mcuntz** [comment]
Descended the version number. Sorry, did it to switch versions during testing.

I also debugged the failing test 'cylinder'. It did not define the single precision integer kind sng_ad in the kind map (it did the double precision dbl_ad, though). This was already in the original 0.2.2 version and is unrelated to my small edit. However, tests work on Python 2.7.16 and 3.7.4 on my machine (macOS 10.14.6) now.

**Comment by mcuntz** [comment]
Just pulled and found a new test: subroutine_contains_issue101.
This test is not working on my system, neither with Python2 nor Python3: it builds a wrapper function for member_procedure but not for member_function.
I consider this unrelated to my patch and leave Balthasar Reuter solving this.

**Comment by jameskermode** [comment]
Thank you - also for fixing the other test. Not sure why your change triggered this regression, but looks all good now.

**Pull request merged**
