### PR TITLE
Fix #206: Parser fails on asterisk

### LINKED ISSUE #206: Parser fails on asterisk in subroutine argument list
Applying `f90wrap` to a code containing old-style routine headers like

```fortran
SUBROUTINE odeint(ystart,nvar,x1,x2,eps,h1,hmin,nok,nbad,derivs,*rkqs)
```

with an asterisk throws an exception

```python
Traceback (most recent call last):
  File "/home/ert/code/.venv/lib/python3.10/site-packages/f90wrap/scripts/main.py", line 304, in main
    parse_tree = fparse.read_files(args.files, doc_plugin_filename=doc_plugin_fname)
  File "/home/ert/code/.venv/lib/python3.10/site-packages/f90wrap/parser.py", line 1538, in read_files
    check = check_subt(cline, file)
  File "/home/ert/code/.venv/lib/python3.10/site-packages/f90wrap/parser.py", line 677, in check_subt
    del (argl[len(argl) - 1])
IndexError: list assignment index out of range
f90wrap: IndexError('list assignment index out of range')
         for help use --help
```

This happens even when the subroutine is skipped by `--skip` which was the workaround in `f2py` before.

Fix: Catch the condition when the header is not identified, e.g. in `parser.py:671` replace

```python
if has_args:
```

by

```python
if has_args and ')' in cl:
```

Then the parser stage is passed and the subroutine can be skipped later.

### PR DESCRIPTION
**Pull request by krystophny**

### CODE REVIEW

**Comment by jameskermode** [comment]
Please can you add a new example that would have caught this problem?

**Review by jameskermode — APPROVED** [review]

**Comment by jameskermode** [comment]
Simple is fine, thanks! Will merge providing CI passes.

**Comment by jameskermode** [comment]
Windows wheels are failing, but that's unrelated so I'll go ahead and merge and open a separate issue for that.

**Comment by krystophny** [comment]
Great, thanks a lot, I really appreciate the fast and efficient workflow! Even though the resulting function is in a kind of strange state (no arguments), I would not invest more time into this issue as such Fortran66 should die out, hopefully. For us it is very useful to have f90wrap run on the code now in any case. Thanks again!

**Pull request merged**
