### PR TITLE
Support doxygen doc for python wrapper

### PR DESCRIPTION
**Pull request by danbeibei**
Parse doxygen documentation in f90 sources and add it to the python wrapper interfaces

### CODE REVIEW

**Comment by jameskermode** [comment]
Thank you for the feature. In principle I'll be happy to merge this providing the CI tests pass. Please could you add something to the README to describe the new functionality?

**Comment by danbeibei** [comment]
Sure, I added a bullet point in the NOTES part

**Comment by danbeibei** [comment]
The tests exemples I wrote uses `pytest` whether than unittest. Is this a problem? 
Is it fine to add pytest as dependancy to the requirements.txt file?

**Comment by jameskermode** [comment]
(The compilation problem affecting wheel building on MacOSX is fixed by #180 so you can ignore that failure, or merge/rebase from https://github.com/jameskermode/f90wrap/tree/macos-latest-wheel-fix into your branch to fix the CI)

**Comment by jameskermode** [comment]
thank you!

**Pull request merged**
