### PR TITLE
Merge Python3 branch into trunk

### PR DESCRIPTION
**Pull request by jameskermode**

### CODE REVIEW

**Comment by hainm** [comment]
nice. can f90wrap works with py3 now, or just WIP?

**Comment by jameskermode** [comment]
There are still a couple of checks to make, but f90wrap should be fully working with Python 3 very soon.

**Comment by jameskermode** [comment]
@citibob would you be able to have a look at these failing Python 3 tests when you have chance? I've fixed the first problem (`iteritems()` -> `items()`), but it looks like will be plenty more... Thanks again for your contribution.

**Comment by hainm** [comment]
you can use six module to write compat code for both py2 and 3.

this should work for  both.
```python
from six import iteritems
for (mod, only) in iteritems(extra_uses_dict):
    pass
```

**Comment by jameskermode** [comment]
Thanks @hainm, I'll bear that in mind - this particular problem is now solved using `dict.items()` directly for Python 2 and 3 compatibility is fine as the number of items will never be so large that the difference between Py `items()` and `iteritems()` behaviour matters.

**Comment by citibob** [comment]
James et al,


Yes, I did use the six interface once.  Unfortunately, that adds another
dependency --- but now that I used it, I suppose the dependency is there,
so why not use it more?


@citibob <https://github.com/citibob> would you be able to have a look at
> these failing Python 3 tests when you have chance? I've fixed the first
> problem (iteritems() -> items()), but it looks like will be plenty
> more...



I'm not sure what this is referring to.  If I have specifics on how to
reproduce the tests, I could probably fix them up pretty easily.

 Thanks @hainm <https://github.com/hainm>, I'll bear that in mind - this
> particular problem is now solved using dict.items() directly for Python 2
> and 3 compatibility is fine as the number of items will never be so large
> that the difference between Py items() and iteritems() behaviour matters.


Yes, that's what I would recommend too.  Returning a list instead of an
iterator is not a problem, even if it's a bit less memory efficient.

-- Bob

**Comment by jameskermode** [comment]
To run the tests locally you just need to do 'make' from the 'examples/' directory. I'm not set up with a Python 3 environment, which is why I enabled Python 3 testing via Travis CI on this branch- if you click the 'Details' link below you can see the current failure point.

**Comment by jameskermode** [comment]
If we can manage without adding six as a dependancy that would be preferable for me - I work with a couple of other codes that work on Python 2.6+ and 3.x simultaneously without too much trouble.

**Comment by hainm** [comment]
six is only a single file, it's BSD. So you can just copy it to your package.

**Comment by citibob** [comment]
OK, I've fixed a bunch more of obvious stuff, in the tests too (see the Python3 branch).  Many tests passed with Python 3.  But without knowing how the same tests work with Python2, I can't say for sure what's going on.  Here's the skinny:

```

sh-3.2$ ls
Makefile		example-derivedtypes	passbyreference
cylinder		example2		todel
example-arrays		mockderivetype
sh-3.2$ cd cylinder/
sh-3.2$ python tests.py 
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
sh-3.2$ python --version
Python 3.4.3
sh-3.2$ cd ../example-arrays/
sh-3.2$ python tests.py 
..F.
======================================================================
FAIL: test_square (__main__.TestExample)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests.py", line 50, in test_square
    np.testing.assert_allclose((x*y + x)**2, co[k,:])
  File "/Users/rpfische/macports/gcc49-python3/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/numpy/testing/utils.py", line 1347, in assert_allclose
    verbose=verbose, header=header)
  File "/Users/rpfische/macports/gcc49-python3/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/numpy/testing/utils.py", line 708, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=1e-07, atol=0

(mismatch 44.891%)
 x: array([                  0,                   4,                  36, ...,
       7756280001446241956, 7760279761451041924, 7764279641452241920])
 y: array([  0.000000e+00,   4.000000e+00,   3.600000e+01, ...,   9.999000e+19,
         9.999400e+19,   9.999800e+19])

----------------------------------------------------------------------
Ran 4 tests in 0.428s

FAILED (failures=1)
sh-3.2$ cd ../example-derivedtypes/
sh-3.2$ python tests.py 
...tests.py:110: DeprecationWarning: Please use assertTrue instead.
  self.assert_(isinstance(dt, self.lib.datatypes.Fixed_Shape_Arrays))
..tests.py:142: DeprecationWarning: Please use assertTrue instead.
  self.assert_(isinstance(ndt.mu.alpha, int)) # boolean/logical in F though)
.tests.py:62: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  br = np.zeros((n,), order='F')
tests.py:63: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  co = np.zeros((4, n), order='F')
.tests.py:35: DeprecationWarning: Please use assertTrue instead.
  self.assert_(isinstance(dt, self.lib.datatypes.Different_Types))
....tests.py:80: DeprecationWarning: Please use assertTrue instead.
  self.assert_(isinstance(dt, self.lib.datatypes.Different_Types))
.tests.py:43: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  br = np.zeros((ndata,), order='F')
tests.py:44: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  co = np.zeros((4, ndata), order='F')
.tests.py:43: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  br = np.zeros((ndata,), order='F')
tests.py:44: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  co = np.zeros((4, ndata), order='F')
....tests.py:110: DeprecationWarning: Please use assertTrue instead.
  self.assert_(isinstance(dt, self.lib.datatypes.Fixed_Shape_Arrays))
..tests.py:142: DeprecationWarning: Please use assertTrue instead.
  self.assert_(isinstance(ndt.mu.alpha, int)) # boolean/logical in F though)
.tests.py:62: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  br = np.zeros((n,), order='F')
tests.py:63: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  co = np.zeros((4, n), order='F')
.tests.py:35: DeprecationWarning: Please use assertTrue instead.
  self.assert_(isinstance(dt, self.lib.datatypes.Different_Types))
....tests.py:80: DeprecationWarning: Please use assertTrue instead.
  self.assert_(isinstance(dt, self.lib.datatypes.Different_Types))
.tests.py:43: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  br = np.zeros((ndata,), order='F')
tests.py:44: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  co = np.zeros((4, ndata), order='F')
.tests.py:43: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  br = np.zeros((ndata,), order='F')
tests.py:44: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  co = np.zeros((4, ndata), order='F')
.
----------------------------------------------------------------------
Ran 28 tests in 0.780s

OK
sh-3.2$ cd ../example-
example-arrays/       example-derivedtypes/ 
sh-3.2$ ls
ExampleDerivedTypes.py			f90wrap_library.f90
ExampleDerivedTypes_pkg			f90wrap_library.o
Makefile				kind_map
README.md				library.f90
_ExampleDerivedTypes.so			library.fpp
_ExampleDerivedTypes.so.dSYM		library.mod
_ExampleDerivedTypes_pkg.so		library.o
_ExampleDerivedTypes_pkg.so.dSYM	libsrc.a
__pycache__				memory_profile.py
datatypes.f90				parameters.f90
datatypes.fpp				parameters.fpp
datatypes.mod				parameters.mod
datatypes.o				parameters.o
datatypes_allocatable.mod		src.macosx-10.9-x86_64-3.4
f90wrap_datatypes.f90			tests.py
f90wrap_datatypes.o
sh-3.2$ cd ..
sh-3.2$ ls
Makefile		example-derivedtypes	passbyreference
cylinder		example2		todel
example-arrays		mockderivetype
sh-3.2$ cd example2
sh-3.2$ ls *.py
mockdt.py	test_module.py	test_package.py
sh-3.2$ python test_module.py 
1,2,3,4 as done by subroutine are 
1.0 2.0 3.0 4.0
<class 'int'>
all tests passed, OK!
sh-3.2$ python test_package.py 
Traceback (most recent call last):
  File "test_package.py", line 15, in <module>
    import mockdtpkg as md
  File "/Users/rpfische/git/f90wrap/examples/example2/mockdtpkg/__init__.py", line 1, in <module>
    import _mockdtpkg
ImportError: No module named '_mockdtpkg'
sh-3.2$ cd ../mockderivetype/
sh-3.2$ ls
Makefile			f90wrap_toplevel.o
Makefile.ifort			fwrap.f90
__pycache__			fwrap.fpp
_mockdt.so			fwrap.o
_mockdt.so.dSYM			horrible.mod
_mockdtpkg.so			kind_map
_mockdtpkg.so.dSYM		leveltwomod.f90
define.f90			leveltwomod.fpp
define.fpp			leveltwomod.mod
define.o			leveltwomod.o
define_a_type.mod		libsrc.a
f90wrap_define.f90		mockdt.py
f90wrap_define.o		mockdtpkg
f90wrap_fwrap.f90		readme.rst
f90wrap_fwrap.o			src.macosx-10.9-x86_64-3.4
f90wrap_leveltwomod.f90		test.py
f90wrap_leveltwomod.o		testpkg.py
f90wrap_toplevel.f90		use_a_type.mod
sh-3.2$ python test.py 
sh-3.2$ python testpkg.py 
sh-3.2$ cd ../passbyreference/
sh-3.2$ ls
__pycache__		f90wrap_mycode.f90	mymodule.mod
_mymodule.so		makefile		mymodule.py
_mymodule.so.dSYM	mycode.F90		mymodule.pyc
example_mymodule.py	mycode.o
sh-3.2$ python example_mymodule.py 
********* BEFORE
b= 17
tt= <mytype>{
    val : 17.0}
 Running mysubroutine
********* AFTER
b= 8
tt= <mytype>{
    val : 12.0}
sh-3.2$ 
```

**Comment by citibob** [comment]
Thanks, done!

-- Bob

**Comment by jameskermode** [comment]
Thanks so much for fixing these @citibob. I'll get a Python 3 installation working somewhere and have a look at the remaining issues ASAP. According to Travis-CI all tests are still passing with Python 2.6 and 2.7: see https://travis-ci.org/jameskermode/f90wrap/builds/85405611 for details

**Comment by citibob** [comment]
So far, Python3 errors on Travis-CI are on "import numpy."  Looks like a
configuration issue with Travis.  But wow, Travis-CI looks like a really
neat system, once it's gotten working!

**Comment by jameskermode** [comment]
All tests passing :-) Merged into master branch.

**Comment by hainm** [comment]
awesome.

**Pull request closed without merging**
